-- ApplyForge bootstrap schema reference.
-- This file documents the initial schema intent while the runtime still uses `Base.metadata.create_all`.
-- Move this into a proper Alembic revision before production rollout.
